apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  values:    # Make this run on the main kind node
    controller:
      tolerations:
      - key: "realnode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: end-to-end-test-control-plane
      admissionWebhooks:
        patch:
          tolerations:
          - key: "realnode"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          nodeSelector:
            kubernetes.io/hostname: end-to-end-test-control-plane
