---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  interval: 1m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.5
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
      interval: 1m
  install:
    remediation:
      retries: 5
  values:
    installCRDs: false
    prometheus:
      servicemonitor:
        enabled: false
