---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
spec:
  values:
    cloudProvider: kwok
    autoDiscovery:
      clusterName: "end-to-end-test"
    nodes:
      skipTaint: true

    # Make this run on the main kind node
    nodeSelector:
      kubernetes.io/hostname: end-to-end-test-control-plane
    tolerations:
    - key: "realnode"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
