---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller

spec:
  interval: 5m
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart:  aws-load-balancer-controller
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: eks-charts
      interval: 1m
  values:
    clusterName: test
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${aws_load_balancer_controller_service_account_role_arn}
