apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${aws_region}
