apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/ingress-system
- ../../base/oauth2-proxy
- ../../base/monitoring-system
- ../../base/logging-system
- ../../base/db-operator-system
- ../../base/gemini
- ../../base/template-controller
- ../../base/temporal
patches:
- target:
    kind: HelmRelease
    name: ingress-nginx
    namespace: ingress-system
  path: patches/run-on-realnode/ingress-nginx.yaml
- target:
    kind: HelmRelease
    name: template-controller
    namespace: template-controller
  path: patches/run-on-realnode/template-controller.yaml
