---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./system/clusters/test-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      cluster: test-cluster
  postBuild:
    substitute:
      cluster_name: test-cluster
      cluster_domain: test-cluster.elifesciences.org
      aws_account_id: 512686554592
      aws_region: us-east-1
