---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-ebs-general-purpose
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  fsType: ext4
  type: gp2
