---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-ebs-throughput-optimised
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  fsType: ext4
  type: st1
