---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  values:
    # Make this run on the main kind node
    nodeSelector:
      kubernetes.io/hostname: end-to-end-test-control-plane
    tolerations:
    - key: "realnode"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    webhook:
      nodeSelector:
        kubernetes.io/hostname: end-to-end-test-control-plane
      tolerations:
      - key: "realnode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    cainjector:
      nodeSelector:
        kubernetes.io/hostname: end-to-end-test-control-plane
      tolerations:
      - key: "realnode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    startupapicheck:
      nodeSelector:
        kubernetes.io/hostname: end-to-end-test-control-plane
      tolerations:
      - key: "realnode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
