---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: end-to-end-test-control-plane
      tolerations:
      - key: "realnode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
