---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  values:
    args:
    - --kubelet-insecure-tls
    # Make this run on the main node
    nodeSelector:
      kubernetes.io/hostname: end-to-end-test-control-plane
    tolerations:
    - key: "realnode"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
