---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  version: "1.27"
  tags:
    Cluster: test-cluster

nodeGroups:
  - name: ng1
    instanceType: t3.large
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        ebs: true
        externalDNS: true
        awsLoadBalancerController: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
    roleName: cluster-autoscaler-aws-cluster-autoscaler

iamIdentityMappings:
  - arn: arn:aws:iam::512686554592:user/ScottAubrey
    groups:
      - system:masters
    username: scottaubrey
  - arn: arn:aws:iam::512686554592:user/nathanlisgo
    groups:
      - system:masters
    username: nathanlisgo

addons:
- name: coredns
- name: kube-proxy
- name: aws-ebs-csi-driver
- name: vpc-cni

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "elifesciences"
      repository: "elife-clusters"
      branch: "master"
      path: "clusters/test-cluster/flux"
      components-extra: "image-reflector-controller,image-automation-controller"
      read-write-key: "true"

# karpenter:
#   version: 'v0.29.2'
#   createServiceAccount: true
