apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service_type: system
resources:
- ../../base/kube-system
- ../../base/certificate-system
- ../../base/autoscaler-system
- ../../base/metrics-server
- ../../base/external-dns
- ../../base/external-secrets
patches:
- target:
    kind: HelmRelease
    name: cluster-autoscaler
  path: patches/cluster-autoscaler.yaml
