---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1m
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 1m
  install:
    remediation:
      retries: 5

  values:
    replicaCount: 1
    txtOwnerId: ${cluster_name}
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        memory: 50Mi
        cpu: 10m
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${external_dns_service_account_role_arn}
