apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: certificate-system
commonLabels:
  service: cert-manager
resources:
- letsencrypt-staging.yaml
- letsencrypt-prod.yaml
- release.yaml
- source.yaml
