apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service_type: system
resources:
- ../../base/kube-system
- ../../base/certificate-system
- ../../base/autoscaler-system
- ../../base/metrics-server
- ../../base/external-dns
- ../../base/external-secrets
- services/aws-load-balancer-controller
- storage-classes/eks-remove-default
- storage-classes/csi-ebs
- volume-snapshot-classes/csi-ebs
- secret-store
patches:
- target:
    kind: HelmRelease
    name: cluster-autoscaler
  path: patches/cluster-autoscaler.yaml
