---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.29.1
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
      interval: 1m
  values:
    image:
      tag: v1.27.2
    autoDiscovery:
      clusterName: ${cluster_name}
      tags:
      - kubernetes.io/cluster/${cluster_name}
    awsRegion: ${aws_region}
    rbac:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: ${autoscaler_service_account_role_arn}
