apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service_type: system
resources:
- ../../classes/kind
- secret-store
patches:
- target:
    kind: HelmRelease
    name: cluster-autoscaler
    namespace: autoscaler-system
  path: patches/cluster-autoscaler/kwok-provider.yaml
- target:
    kind: Deployment
    name: external-snapshotter
    namespace: kube-system
  path: patches/run-on-realnode/external-snapshotter.yaml
- target:
    kind: HelmRelease
    name: cert-manager
    namespace: certificate-system
  path: patches/run-on-realnode/cert-manager.yaml
- target:
    kind: HelmRelease
    name: external-secrets
    namespace: external-secrets
  path: patches/run-on-realnode/external-secrets.yaml
- target:
    kind: HelmRelease
    name: metrics-server
    namespace: metrics-server
  path: patches/run-on-realnode/metrics-server.yaml
- target:
    kind: HelmRelease
    name: descheduler
    namespace: kube-system
  path: patches/run-on-realnode/descheduler.yaml
- target:
    kind: HelmRelease
    name: sealed-secrets
    namespace: kube-system
  path: patches/run-on-realnode/sealed-secrets.yaml
configMapGenerator:
- name: kwok-provider-config
  namespace: autoscaler-system
  files:
  - config=config/kwok-provider-config.yaml
  options:
    disableNameSuffixHash: true
- name: kwok-provider-templates
  namespace: autoscaler-system
  files:
  - templates=config/kwok-provider-templates.yaml
  options:
    disableNameSuffixHash: true
