apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service_type: system
resources:
- ../../classes/kind
- secret-store
patches:
- target:
    kind: HelmRelease
    name: cluster-autoscaler
    namespace: autoscaler-system
  path: patches/cluster-autoscaler/kwok-provider.yaml
- target:
    kind: HelmRelease
    name: cert-manager
    namespace: certificate-system
  path: patches/cluster-autoscaler/cert-manager.yaml
configMapGenerator:
- name: kwok-provider-config
  namespace: autoscaler-system
  files:
  - config=config/kwok-provider-config.yaml
  options:
    disableNameSuffixHash: true
- name: kwok-provider-templates
  namespace: autoscaler-system
  files:
  - templates=config/kwok-provider-templates.yaml
  options:
    disableNameSuffixHash: true
