apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service_type: system
resources:
- ../../classes/kind
- secret-store
patches:
- target:
    kind: HelmRelease
    name: cluster-autoscaler
  path: patches/cluster-autoscaler.yaml
