---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
spec:
  values:
    image:
      tag: v1.29.0
    cloudProvider: kwok
    autoDiscovery:
      clusterName: "end-to-end-test"
    nodes:
      skipTaint: true
    kwokConfigMapName: kwok-provider-config

    # Make this run on the main kind node
    nodeSelector:
      kubernetes.io/hostname: end-to-end-test-control-plane
    tolerations:
    - key: "realnode"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: ClusterRole
        patch: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: cluster-autoscaler-kwok-cluster-autoscaler
          rules:
          - apiGroups:
            - ""
            resources:
            - configmaps
            resourceNames:
            - kwok-provider-config
            - kwok-provider-templates
            verbs:
            - get
          - apiGroups:
            - ""
            resources:
            - nodes
            resourceNames:
            verbs:
            - create
            - delete
            - update
            - get
