apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-node-0
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
  name: kwok-node-0
spec:
  # taints: # Avoid scheduling actual running pods to fake Node
  #   - effect: NoSchedule
  #     key: kwok.x-k8s.io/node
  #     value: fake
status:
  allocatable:
    cpu: 1930m
    memory: 7265224Ki
    pods: 35
    ephemeral-storage: 20Gi
  capacity:
    cpu: 2
    memory: 8Gi
    pods: 35
    ephemeral-storage: 20Gi
  nodeInfo:
    architecture: amd64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running
