---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 1m
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.18.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      interval: 1m
  values:

    ingress:
      enabled: "true"
      hosts:
        - auth.${cluster_domain}
      tls:
      - secretName: oauth2-proxy-cert
        hosts:
        - auth.${cluster_domain}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    extraArgs:
      provider: github
      github-org: elifesciences
      whitelist-domain: .elifesciences.org
      cookie-domain: .elifesciences.org
      scope: "user:email"
      set-xauthrequest: true
    replicaCount: 2
